### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by andreydk1981** [zbx-sadman/Zabbuino#10]
Здравствуйте.
Попробовал версию 1.4 - у меня не работает кнопка reset.
Прошиваю обратно на 1.3 - работает.

Видимо какая то ошибка появилась в новой версии.

**Comment by zbx-sadman** [comment]
Hello

Reset чего - контроллера или "Factory Reset"?

**Comment by andreydk1981** [comment]
Factory Reset. Из за этого не получается новый ip адрес после перепрошивки присвоить. Я знаю, что его можно присвоить командой, но мне кнопкой проще. 


Замыкаю пин 8 на землю,  включаю питание и ничего не происходит - просто начинает работать заббуино. 
А на версии 1.3 загорется state led, потом начинает быстро мигать (как в инструкции)

**Comment by zbx-sadman** [comment]
Светодиода у меня под рукой нет, но адрес сбрасывается вполне себе удачно, насколько я вижу:

![image](https://user-images.githubusercontent.com/12827470/76056457-a6b00a80-5f87-11ea-8084-174bc10e1b5d.png)

**Comment by zbx-sadman** [comment]
Проверил со светодиодом - всё ОК. 

Возможно, что в конфиге для v1.3 был переназначен с дефолтового пин для "State LED".

**Comment by andreydk1981** [comment]
Разобрался.... забыл включить запись в EEPROM. Включил и всё стало как нужно. Извиняюсь... Очень крутой продукт у вас!
