### ISSUE TITLE
Sorry but what is the meaning of ACK H and ACK L

### ISSUE THREAD

**Issue by healperci** [zbx-sadman/Zabbuino#11]
Sorry but I'm documenting a Arduino proyect based in Zabbuino.

The Firmware is working pretty good.

But from time to time I have a :"131"communication "133" ACK L  "-134" ACK H and " errors in the zabbix platform.

Is ok to have a sampling bad but In the docs I have to put what does mean each Ackowledge 

Does ¿H means High? And ¿L means low? and is it ¿low o High of what? 

Thanks for the firmware, the proyect of datalogger was so simple thanks to Your work...

**Comment by zbx-sadman** [comment]
"ACK L/H" is error codes for DHT-sensor query stages. 

It have no any special meaning, just this is very old part of code and i really do not remember why i  used separate error code for all stages ☺️

Anyway - both of this code is signalize that DHT does not answer properly.
