### ISSUE TITLE
   Заббуино и pzem004t v 3.0

### ISSUE THREAD

**Issue by Natashaarduino** [zbx-sadman/Zabbuino#14]
Добрый день. Тестирую подключение датчиков pzem004t v 3.0 (с модбус) и ds18s20 к ардуино uno с чипом wiznet 5500  и системе мониторинга zabbix. Температура выводится четко, графики строятся отлично. Спасибо большое за программу. А с  #энергодатчиком возникла проблема. Я так понимаю, библиотека для работы с ним modbus.h. При подключении выдает нули. Ранее датчик был подключен отдельно без заббуино с помощью библиотеки pzem004tv30.h, все работало. Нужно отдельно устанавливать адрес или достаточно в zabbix прописать _slaveId?

**Comment by Natashaarduino** [comment]
Добавлю, что была активирована функция Feature_modbus_rtu_enable.

**Comment by zbx-sadman** [comment]
Hello

Поддержка PZEM-004 с протоколом modbus не реализована. У меня нет этого устройства для отладки.

**Comment by Natashaarduino** [comment]
А як можна передати Вам цей пристрій для розвитку проекту?

**Comment by zbx-sadman** [comment]
По передаче именно устройства даже идей не имею. Из Украины в Россию сложновато, полагаю, будет засылать.

Но, если идеи есть, то пишите на имейл.

**Comment by Natashaarduino** [comment]
Спасибо.
