### ISSUE TITLE
PZEM-004 замена адреса

### ISSUE THREAD

**Issue by ProVinciall** [zbx-sadman/Zabbuino#8]
Если есть возможность, пожалуйста, добавьте команду замены адреса setAddress для PZEM.
Планирую использовать ваш код обработки данных с 3-хфазной нагрузки
 с подключением 3-х PZEM на один COM-порт.
Вот пример реализации https://wiki.cuvoodoo.info/doku.php?id=spark_abacus#peacefair_pzem-004t

Спасибо за ваш проект.

**Comment by zbx-sadman** [comment]
Добавить, в принципе смогу, но проверить - наврядли. Пока нет возможности развернуть "испытательный полигон". Напишите мне на e-mail, если сможете сразу оттестить, потому что неизвестно как работающий код я не буду включать в Zabbuino.

**Comment by zbx-sadman** [comment]
По результатам испытаний @ProVinciall  установлено, что параллельно соединенные устройства PZEM004 будут корректно работать в том случае, когда у всех экземпляров, за исключением одного, будут удалены R15 в цепях оптрона вывода RX.

![image](https://cloud.githubusercontent.com/assets/12827470/24908925/aead066c-1eca-11e7-9d65-822013f4abf2.png)

**Comment by ProVinciall** [comment]
Только-что закончил схему и скрины.


>Вторник, 11 апреля 2017, 15:25 +03:00 от Grigory Prigodin <notifications@github.com>:
>
>Closed  #8 .
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .



---
bralex@mail.ru

**Comment by ProVinciall** [comment]
Было проведено тестирование двух параллельно соединенных плат PZEM-004t с различными адресами  на один SoftSerial в Arduino.
![zabbuino-pzem-2017-04-11](https://cloud.githubusercontent.com/assets/26900043/24909430/87946212-1ecc-11e7-9982-14320ba86b93.png)
